### PR TITLE
 set up group project with create reatjs app

### PR DESCRIPTION
**Pull request by Eliasadam**

### CODE REVIEW

**Comment by Samatar26** [comment]
LGTM

**Comment by Saravanan21** [comment]
Adding a .gitignore to skip the `node_modules` folder is recommended. If you do a search on google you may find other suggested things to add to gitignore for a React project as well.

**Comment by Samatar26** [comment]
@Saravanan21 he has added a .gitignore file in the pull request.

**Comment by Saravanan21** [comment]
Oh I missed that - I still see lots of node_modules files checked in though so were presumably added first hence committed

**Comment by Samatar26** [comment]
@rajgthub Nice catch! @Eliasadam You have to delete the node_modules folder, commit and push again.

**Pull request merged**
